# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 1.0$(Rev:.r)

trigger:
- master

variables:
 creator : 'thomas'

pool:
  vmImage: 'ubuntu-latest'

# first stage
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building! - Created by $(creator)
    
# second stage
- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - pwsh: |
        Write-Host "This multiline script always runs in PowerShell Core."
        Write-Host "Even on non-Windows machines!"
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
    
# third stage
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!
